### PR TITLE
Made sunflower and wildflower classes. Made ICompostProducing interface

### PR DESCRIPTION
**Pull request by warnercarpenter**
# Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Testing Instructions for Change Made
1. `git fetch --all`
1. `git checkout NAME-OF-BRANCH`
1. dotnet run
1. verify...

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by MoSilvera** [comment]
👍

**Comment by MoSilvera** [comment]
Also.. great description. Should win a pulitzer.

**Comment by warnercarpenter** [comment]
Leave a comment

**Comment by emmettSchneider** [comment]
> Leave a comment

Comment.

**Pull request merged**
